### ISSUE TITLE
Lambdas are forbidden in JSX attributes.

### ISSUE THREAD

**Issue by JohnFrolov** [DedVorchun/TaskOne#1]
https://github.com/DedVorchun/TaskOne/blob/be5855516e381bc08e4173efafd977f40ab64269/src/Typeahead.js#L11

Creating lambdas inside the render call stack works against pure component rendering. When doing an equality check between two lambdas, React will always consider them unequal values and force the component to re-render more often than necessary.

for more information, you can read  this thread:
https://stackoverflow.com/questions/55001372/correct-way-to-create-event-handlers-using-hooks-in-react

**Comment by DedVorchun** [comment]
Fix
https://github.com/DedVorchun/TaskOne/blob/dba26e63a9da479c3107d68aec140c565b7509ce/src/Typeahead.js#L69
